# Generated by Django 3.0.4 on 2020-03-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('link', models.URLField(max_length=100)),
                ('tracklist', models.URLField(max_length=100)),
            ],
        ),
    ]
